In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits=load_digits()

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3,random_state=10)

### Logistic

In [10]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9629629629629629

### SVM

In [11]:
svm=SVC(kernel='linear')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9814814814814815

### random forest

In [12]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9648148148148148

Now we have calculated scores from 3 algos with some imp or main parameters now we can check with cross validations and stuff to know much more accurate score

## KFold cross validation

In [13]:
from sklearn.model_selection import KFold

In [14]:
kf=KFold(n_splits=10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [15]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [17]:
from sklearn.model_selection import StratifiedKFold
#folds=StratifiedKFold(folds=10)
# scores_logistic = []
# scores_svm = []
# scores_rf = []

# for train_index, test_index in folds.split(digits.data,digits.target):
#     X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
#                                        digits.target[train_index], digits.target[test_index]
#     scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
#     scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
#     scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

### cross_val_score function

In [30]:
from sklearn.model_selection import cross_val_score
lr_score=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=10)
lr_score

array([0.91111111, 0.93888889, 0.89444444, 0.86666667, 0.94444444,
       0.97222222, 0.97777778, 0.94972067, 0.8603352 , 0.94413408])

In [33]:
lr_score.mean()

0.9259745499689634

In [35]:
svm_score=cross_val_score(SVC(kernel='linear'), digits.data, digits.target,cv=10)
svm_score

array([0.93888889, 0.99444444, 0.93333333, 0.94444444, 0.96111111,
       0.98888889, 0.96666667, 0.97765363, 0.93296089, 0.96648045])

In [36]:
svm_score.mean()

0.9604872749844816

In [37]:
rf_score=cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target,cv=10)
rf_score

array([0.9       , 0.97222222, 0.94444444, 0.90555556, 0.96111111,
       0.97222222, 0.97777778, 0.97206704, 0.95530726, 0.92178771])

In [38]:
rf_score.mean()

0.9482495344506517

Further for more accuracy and precision we can do more hyper parameter tuning and find the score in the similar way